### PR TITLE
Updating to work with new config file & directory structure

### PR DESCRIPTION
**Pull request by tadhg-moore**
Updated all the functions & vignettes & examples to match the new structure.

### CODE REVIEW

**Comment by tadhg-moore** [comment]
Currently crashing building on Ubuntu - related to the vignettes but it is passing on Win & Mac. Any ideas/suggestions welcome!

**Comment by tadhg-moore** [comment]
Fixed the vignettes by declaring rmarkdown instead of knitr in DESCRIPTION for VignetteBuilder

**Comment by rqthomas** [comment]
I am wondering if it is possible to clean files out of the inst/ folder.  Is the testing only using the files in the example subdirectory?

**Comment by tadhg-moore** [comment]
Good catch, just removed them!

**Pull request merged**
